parser: babel-eslint
parserOptions:
  ecmaVersion: 6
globals:
  test: true
  expect: true
extends:
  - airbnb-base
  - prettier
  - plugin:flowtype/recommended
plugins:
  - flowtype
  - prettier
rules:
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: none
  valid-jsdoc: error
